# All flashcard information was generated by Gemini 3 Pro. 
# No code was generated by Generative AI.

flashcard_set_1 = {
    1: ("A code segment assigns a ← 10 and b ← 20. It then executes a ← b followed by b ← a. What are the final values of a and b?", "a = 20, b = 20. (The original value of a was overwritten in the first step)."),
    2: ("Which of the following best describes an undecidable problem?", "A problem for which no algorithm can be constructed that is always capable of providing a correct yes or no answer."),
    3: ("A list numbers contains [10, 20, 30, 40]. What is displayed by the code: DISPLAY(numbers[2] + numbers[4])?", "60 (AP CSP lists are 1-indexed, so index 2 is 20 and index 4 is 40)."),
    4: ("A binary search is performed on a sorted list of 1,000 elements. What is the approximate maximum number of comparisons needed?", "10 or 11 (Since 2^10 = 1024, it takes about 10 steps to halve the list down to one item)."),
    5: ("What is the primary difference between a simulation and a real-world experiment?", "Simulations allow testing of hypotheses that might be too dangerous, expensive, or time-consuming to perform in the real world."),
    6: ("Which of the following is true about heuristics in programming?", "They provide a solution that is good enough (approximate) when an exact solution is unreasonable to compute."),
    7: ("If a robot uses the logic REPEAT UNTIL (GoalReached) to navigate a maze, what type of iteration is this?", "Indefinite Iteration (The number of steps is not known when the loop starts)."),
    8: ("Which feature of a procedure (function) helps most with code reuse and reducing complexity?", "Parameters (They allow the procedure to generalize its behavior for different input values)."),
    9: ("A program checks IF (grade > 90). If this is false, it checks ELSE IF (grade > 80). If a student has an 85, which block runs?", "Only the ELSE IF (grade > 80) block runs."),
    10: ("Two boolean variables, isValid and isReady, are both FALSE. What does (NOT isValid) AND (NOT isReady) evaluate to?", "TRUE. (NOT False = True. So it becomes True AND True)."),
}


flashcard_set_2 = {
    1: ("How does the Internet handle a file sent from one computer to another?", "The file is broken into packets, which may take different paths and arrive out of order, and are reassembled by the receiving device."),
    2: ("What feature allows the Internet to continue operating properly even if a specific connection or router fails?", "Fault Tolerance (achieved through Redundancy)."),
    3: ("Which of the following best describes the Digital Divide?", "Differences in access to computing devices and the Internet based on socioeconomic, geographic, or demographic characteristics."),
    4: ("What is the main function of the Transmission Control Protocol (TCP)?", "It manages the reliable transmission of data, including error-checking and requesting the re-transmission of missing packets."),
    5: ("Why does the Internet use open, non-proprietary standards (like HTTP and IP)?", "To ensure interoperability, allowing devices from different manufacturers to communicate without restriction."),
    6: ("In public key encryption, if User A wants to send a secure message to User B, which key does User A use to encrypt the message?", "User B's Public Key. (Only User B's Private Key can then decrypt it)."),
    7: ("A system adds more servers to handle increased traffic without noticing a drop in performance. What property is this?", "Scalability."),
    8: ("What is a Distributed Denial of Service (DDoS) attack?", "An attempt to overwhelm a server with traffic from many different sources to make it unavailable to legitimate users."),
    9: ("What is the relationship between bandwidth and latency?", "Bandwidth is the amount of data that can be sent in a fixed time; Latency is the time it takes for a single piece of data to travel."),
    10: ("What is the purpose of a Digital Certificate?", "It verifies that a public key belongs to a specific entity, preventing impostors from intercepting secure data."),
}


flashcard_set_3 = {
    1: ("A social media site uses an algorithm to populate user feeds. Why might this algorithm inadvertently create echo chambers?", "The algorithm is optimized to maximize engagement, so it filters out opposing viewpoints to show users content that aligns with their beliefs."),
    2: ("Which Creative Commons license allows others to use a work, but only if they give credit and do not make money from it?", "CC BY-NC (Attribution-NonCommercial)."),
    3: ("What is Crowdsourcing?", "Obtaining information, work, or funding from a large group of people via the Internet."),
    4: ("A photo sharing app stores metadata with every picture. What is an example of a privacy risk associated with metadata?", "The metadata might contain the GPS coordinates of where the photo was taken, revealing the user's home location."),
    5: ("What is the most likely source of bias in a Machine Learning algorithm?", "The data used to train the algorithm was not representative of the entire population."),
    6: ("What is Phishing?", "A social engineering attack where a bad actor sends a deceptive email to trick a user into revealing a password."),
    7: ("What is the Citizen Science model?", "Scientific research where data collection or analysis is performed by members of the general public."),
    8: ("What is the difference between Open Source and Freeware?", "Open Source makes the actual source code available for inspection; Freeware is free to use but the code is hidden."),
    9: ("A user logs into a site using a password and a code sent to their phone. What is this called?", "Multifactor Authentication (MFA)."),
    10: ("Why is it difficult to legally protect software algorithms under copyright law compared to books or music?", "Copyright protects the expression of an idea (the specific code), but not the functional logic or math behind the algorithm itself."),
}


db = [
    ("Algorithms & Programming", flashcard_set_1), 
    ("Computing Systems & Networks", flashcard_set_2), 
    ("Impact of Computing", flashcard_set_3),
    ]
